# Site settings
title: Abigail Noyce
email: anoyce@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  Abigail Noyce is a cognitive neuroscientist who studies human attention and 
  short-term memory.
baseurl: "/anoyce" # the subpath of your site, e.g. /blog/
url: "http://people.bu.edu" # the base hostname & protocol for your site
twitter_username: abbynoyce
github_username:  abbynoyce

# Build settings
markdown: kramdown
